### PR TITLE
Add note about disconnects

### PR DESCRIPTION
**Pull request by boehs**
Happened to me /shrug

### CODE REVIEW

**Comment by davegson** [comment]
Hi @boehs, thanks for the pull request. Having the Internet cut off while setting up the filter lists is definitely unintended behavior, sorry this happened!

However, I am unhappy solving this with an extensive warning message. I feel our strong branding of Portmaster being in "alpha" already communicates these kind of hick-ups can occur.

So instead of adding a warning, I would much rather get to the root of this issue and fix it, rendering such a message superfluous. Would you agree with this take? Would it be possible to [open up a bug report](https://github.com/safing/portmaster/issues/new?assignees=&labels=bug&template=report-bug.md) when this happens again?

**Comment by davegson** [comment]
closing for now, however you are welcome to comment and advocate for a different strategy

**Comment by davegson** [comment]
as an update, this seems to happen more often than I assumed:
https://old.reddit.com/r/safing/comments/p31gr3/portmaster_doesnt_load_and_cuts_off_connection/

did it also completely shut off the Internet for you until you uninstalled/stopped the Portmaster?

**Comment by boehs** [comment]
Sorry, was on a long trip. Do you need anything anymore? It seems the reddit thread was useful

**Pull request closed without merging**
